__title__ = 'Datastore-Entity'
__description__ = 'An ORM-Like interface for Google Cloud NoSQL Datastore'
__url__ = 'https://github.com/komlasapaty/datastore-entity'
__version_info__ = ('0', '2', '0')
__version__ = '.'.join(__version_info__)
__author__ = 'Seyram Komla Sapaty'
__author_email__ = 'komlasapaty@gmail.com'
__maintainer__ = 'Seyram Komla Sapaty'
__license__ = 'MIT'
__copyright__ = '(c) 2020 by Seyram Komla Sapaty'
